@startuml
[Клиент, использующий внешнее API]

folder "Сервер" {
    [API View]
    [Model]
    [Serializer]

    database "PostgreSQL"
}

[Клиент, использующий внешнее API] --> [API View]: 1. HTTP запрос
[API View] --> [Клиент, использующий внешнее API]: 8. HTTP ответ 

[API View] --> [Model]: 2. Запрос к модели \n запрашиваемых данных
[Model] --> [API View]: 5. Данные передаются \n в ответ

[API View] --> [Serializer]: 6. Сериализация данных
[Serializer] --> [API View]: 7. Возвращаются сериализированные данные

' Нужно ли пояснять, что имеется в виду на диаграмме? Например, что такое сериализация данных

[Model] --> [PostgreSQL]: 3. Через Django ORM \n формируется SQL запрос в БД
[PostgreSQL] --> [Model]: 4. Из БД возвращаются \n запрошенные данные
@enduml