@startuml
actor Пользователь as User
User -> View : Запрос страницы формы редактирования плана \n (GET Request)

View -> Form : Запрос на формы редактирования плана
Form -> Model : Запрос на данные плана
database "База данных" as Database
Model -> Database : Запрос на данные плана
Database -> Model : Получение данных о плане
Model -> View : Получение объекта плана

View -> Model : Проверка, есть ли у пользователя \n права на верификацию плана
Model -> Database : Запрос на данные о пользователе
Database -> Model : Получение данных о пользователе
Model -> View : Получение объекта пользователя

alt Если у пользователя есть право на верификацию плана
    View -> Template : Рендер HTML-страницы с полем верификации плана
    Template -> View : Возвращение HTML-страницы
    View -> User : Возвращается HTTP Response
    User -> User: Отмечает, что план верифицирован или не верифицирован
else Если у пользователя нет права на верификацию плана
    View -> Template : Рендер HTML-страницы без поля верификации плана
    Template -> View : Возвращение HTML-страницы
    View -> User : Возвращается HTTP Response
end

User -> View: Сохраняет план \n (POST Request)
View -> Form : Валидация данных формы
Form -> View : Возвращаются провалидированные данные
View -> Model : Изменение объекта плана
Model -> Database : Сохранение объекта
Database -> Model : Подтверждение того, что объект сохранен
Model -> View : Возвращение созданного объекта
View -> Template : Рендер HTML-страницы с сообщением, что объект успешно создан
Template -> View : Возвращение HTML-страницы
View -> User : Возвращается HTTP Response
@enduml
